apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: deparrow

resources:
  - namespace.yaml
  - metaos-deployment.yaml
  - metaos-service.yaml
  - gui-deployment.yaml
  - gui-service.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - redis-deployment.yaml
  - redis-service.yaml

configMapGenerator:
  - name: deparrow-config
    literals:
      - LOG_LEVEL=info

secretGenerator:
  - name: deparrow-secrets
    literals:
      - DEPARROW_SECRET_KEY=change-me-in-production
      - POSTGRES_PASSWORD=deparrow
