# HPA staging configuration
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: metaos-hpa
spec:
  minReplicas: 2
  maxReplicas: 5
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gui-hpa
spec:
  minReplicas: 2
  maxReplicas: 4
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: compute-node-dind-hpa
spec:
  minReplicas: 3
  maxReplicas: 10
