# Disable HPA for development
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: metaos-hpa
spec:
  maxReplicas: 1
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gui-hpa
spec:
  maxReplicas: 1
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: orchestrator-hpa
spec:
  maxReplicas: 1
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: compute-node-dind-hpa
spec:
  maxReplicas: 1
